name: 'inscape_media_demo'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  inscape_media_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
